In [1]:
import pandas as pd 
import numpy as np
import string 
import re #regex library

In [2]:
from nltk.tokenize import word_tokenize 
from nltk.probability import FreqDist

In [8]:
def load_data():
    data = pd.read_csv('datacleaning_coba.csv')
    return data

In [10]:
tweet_df = load_data()
tweet_df.head(340)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Created_At,Tweets
0,0,0,0,NaN,tweets
1,1,1,1,2021-10-23 06:55:05+00:00,b'@jibrilss15 @jibrilbangi syukur... done beli...
2,2,2,2,2021-10-23 06:52:15+00:00,b'kesel bgt beli shopeefood lupa nyalain disko...
3,3,3,3,2021-10-23 06:32:42+00:00,b'2 nasi padang lauk ayam sama sayur + es teh ...
4,4,4,4,2021-10-23 06:17:33+00:00,b'@mundur41149832 shopeefood klau ngakpunya sh...
...,...,...,...,...,...
335,335,335,335,2021-10-21 10:27:43+00:00,b'ke circle k jalan kaki cuma 5 mnt tp ak pese...
336,336,336,336,2021-10-21 10:23:24+00:00,b'nasi goreng tiga de nok - palmerah sekarang ...
337,337,337,337,2021-10-21 10:22:48+00:00,b'@balebengong #kamisbisnis\nmasih ada nih dis...
338,338,338,338,2021-10-21 10:09:19+00:00,b'kenapa deh shopeefood makanannya ga ada decs...
339,339,339,339,2021-10-21 10:08:55+00:00,b'guis yuk diorder cemilannya\xe2\x98\xba\xef\...

In [11]:
df  = pd.DataFrame(tweet_df[['Created_At', 'Tweets']])

In [30]:
def remove(tweet):
    #remove angka
    tweet = re.sub('[0-9]+', '', tweet)
    
    # remove tab, new line, ans back slice
    tweet = tweet.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")
 
    # remove non ASCII (emoticon, chinese word, .etc)
    tweet = tweet.encode('ascii', 'replace').decode('ascii')
    
    # remove mention, link, hashtag
    tweet = ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", tweet).split())

    # remove hashtags
    # only removing the hash # sign from the word
    tweet = re.sub(r'#', '', tweet)
    
    #remove punctuation
    tweet = tweet.translate(str.maketrans("","",string.punctuation))
    
    #remove whitespace leading & trailing
    tweet = tweet.strip()
    
    #remove multiple whitespace into single whitespace
    tweet = re.sub('\s+',' ',tweet)

    return tweet
df['remove_http'].apply(lambda x: remove(x))

0                                                 tweets
1                      b syukur done beli via shopeefood
2      bkesel bgt beli shopeefood lupa nyalain diskon...
3      b nasi padang lauk ayam sama sayur es teh cuma...
4      b shopeefood klau ngakpunya shopepay gabisa da...
                             ...
335    bke circle k jalan kaki cuma mnt tp ak pesen l...
336    bnasi goreng tiga de nok palmerah sekarang ada...
337    b masih ada nih diskon di shopeefood nugget rb...
338    bkenapa deh shopeefood makanannya ga ada decs ...
339    bguis yuk diorder cemilannyaxexxbaxefxbxf menu...
Name: remove_http, Length: 340, dtype: object

In [31]:
df

,Created_At,Tweets,remove_user,remove_http
0,NaN,tweets,tweets,tweets
1,2021-10-23 06:55:05+00:00,b'@jibrilss15 @jibrilbangi syukur... done beli...,b' syukur... done beli via shopeefood https:/...,b syukur done beli via shopeefood
2,2021-10-23 06:52:15+00:00,b'kesel bgt beli shopeefood lupa nyalain disko...,b'kesel bgt beli shopeefood lupa nyalain disko...,bkesel bgt beli shopeefood lupa nyalain diskon...
3,2021-10-23 06:32:42+00:00,b'2 nasi padang lauk ayam sama sayur + es teh ...,b'2 nasi padang lauk ayam sama sayur + es teh ...,b nasi padang lauk ayam sama sayur es teh cuma...
4,2021-10-23 06:17:33+00:00,b'@mundur41149832 shopeefood klau ngakpunya sh...,b' shopeefood klau ngakpunya shopepay gabisa d...,b shopeefood klau ngakpunya shopepay gabisa da...
...,...,...,...,...
335,2021-10-21 10:27:43+00:00,b'ke circle k jalan kaki cuma 5 mnt tp ak pese...,b'ke circle k jalan kaki cuma 5 mnt tp ak pese...,bke circle k jalan kaki cuma mnt tp ak pesen l...
336,2021-10-21 10:23:24+00:00,b'nasi goreng tiga de nok - palmerah sekarang ...,b'nasi goreng tiga de nok - palmerah sekarang ...,bnasi goreng tiga de nok palmerah sekarang ada...
337,2021-10-21 10:22:48+00:00,b'@balebengong #kamisbisnis\nmasih ada nih dis...,b' #kamisbisnis\nmasih ada nih diskon di shope...,b masih ada nih diskon di shopeefood nugget rb...
338,2021-10-21 10:09:19+00:00,b'kenapa deh shopeefood makanannya ga ada decs...,b'kenapa deh shopeefood makanannya ga ada decs...,bkenapa deh shopeefood makanannya ga ada decs ...
339,2021-10-21 10:08:55+00:00,b'guis yuk diorder cemilannya\xe2\x98\xba\xef\...,b'guis yuk diorder cemilannya\xe2\x98\xba\xef\...,bguis yuk diorder cemilannyaxexxbaxefxbxf menu...

In [23]:
def remove(tweet):
    #remove angka
    tweet = re.sub('[0-9]+', '', tweet)
    
    # remove tab, new line, ans back slice
    tweet = tweet.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")
 
    # remove non ASCII (emoticon, chinese word, .etc)
    tweet = tweet.encode('ascii', 'replace').decode('ascii')
    
    # remove incomplete URL
    tweet = re.sub(r"http\S+", "", tweet)

    # remove hashtags
    # only removing the hash # sign from the word
    tweet = re.sub(r'#', '', tweet)
    
    #remove punctuation
    tweet = tweet.translate(str.maketrans("","",string.punctuation))
    
    #remove whitespace leading & trailing
    tweet = tweet.strip()
    
    #remove multiple whitespace into single whitespace
    tweet = re.sub('\s+',' ',tweet)

    return tweet
df['remove_http'] = df['remove_user'].apply(lambda x: remove(x))

In [24]:
df

,Created_At,Tweets,remove_user,remove_http
0,NaN,tweets,tweets,tweets
1,2021-10-23 06:55:05+00:00,b'@jibrilss15 @jibrilbangi syukur... done beli...,b' syukur... done beli via shopeefood https:/...,b syukur done beli via shopeefood
2,2021-10-23 06:52:15+00:00,b'kesel bgt beli shopeefood lupa nyalain disko...,b'kesel bgt beli shopeefood lupa nyalain disko...,bkesel bgt beli shopeefood lupa nyalain diskon...
3,2021-10-23 06:32:42+00:00,b'2 nasi padang lauk ayam sama sayur + es teh ...,b'2 nasi padang lauk ayam sama sayur + es teh ...,b nasi padang lauk ayam sama sayur es teh cuma...
4,2021-10-23 06:17:33+00:00,b'@mundur41149832 shopeefood klau ngakpunya sh...,b' shopeefood klau ngakpunya shopepay gabisa d...,b shopeefood klau ngakpunya shopepay gabisa da...
...,...,...,...,...
335,2021-10-21 10:27:43+00:00,b'ke circle k jalan kaki cuma 5 mnt tp ak pese...,b'ke circle k jalan kaki cuma 5 mnt tp ak pese...,bke circle k jalan kaki cuma mnt tp ak pesen l...
336,2021-10-21 10:23:24+00:00,b'nasi goreng tiga de nok - palmerah sekarang ...,b'nasi goreng tiga de nok - palmerah sekarang ...,bnasi goreng tiga de nok palmerah sekarang ada...
337,2021-10-21 10:22:48+00:00,b'@balebengong #kamisbisnis\nmasih ada nih dis...,b' #kamisbisnis\nmasih ada nih diskon di shope...,b kamisbisnis masih ada nih diskon di shopeefo...
338,2021-10-21 10:09:19+00:00,b'kenapa deh shopeefood makanannya ga ada decs...,b'kenapa deh shopeefood makanannya ga ada decs...,bkenapa deh shopeefood makanannya ga ada decs ...
339,2021-10-21 10:08:55+00:00,b'guis yuk diorder cemilannya\xe2\x98\xba\xef\...,b'guis yuk diorder cemilannya\xe2\x98\xba\xef\...,bguis yuk diorder cemilannyaxexxbaxefxbxf menu...

In [ ]:
def remove(tweet):
    #remove angka
    tweet = re.sub('[0-9]+', '', tweet)
    
    # remove stock market tickers like $GE
    tweet = re.sub(r'\$\w*', '', tweet)
 
    # remove old style retweet text "RT"
    tweet = re.sub(r'^RT[\s]+', '', tweet)
    
    # remove hashtags
    # only removing the hash # sign from the word
    tweet = re.sub(r'#', '', tweet)
    return tweet
df['remove_http'] = df['remove_user'].apply(lambda x: remove(x))

In [9]:
def remove_tweet_special(text):
    # remove tab, new line, ans back slice
    text = text.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\',"")
    # remove non ASCII (emoticon, chinese word, .etc)
    text = text.encode('ascii', 'replace').decode('ascii')
    # remove mention, link, hashtag
    text = ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", text).split())
    # remove incomplete URL
    return text.replace("http://", " ").replace("https://", " ")

In [14]:
TWEET_DATA['Tweet_Special'] = TWEET_DATA['Tweet_Special'].apply(remove_tweet_special)

KeyError: 'Tweet_Special'

In [11]:
print(TWEET_DATA['Tweets'].head(340))

0                                                 tweets
1                  b' syukur... done beli via shopeefood
2      b'kesel bgt beli shopeefood lupa nyalain disko...
3      b'2 nasi padang lauk ayam sama sayur + es teh ...
4      b' shopeefood klau ngakpunya shopepay gabisa d...
                             ...
335    b'ke circle k jalan kaki cuma 5 mnt tp ak pese...
336    b'nasi goreng tiga de nok - palmerah sekarang ...
337    b' masih ada nih diskon di shopeefood. nugget ...
338    b'kenapa deh shopeefood makanannya ga ada decs...
339    b'guis yuk diorder cemilannyaxe2x98xbaxefxb8x8...
Name: Tweets, Length: 340, dtype: object

In [13]:
def remove_tweet_special()

ValueError: Wrong number of items passed 5, placement implies 1